---
- hosts: all
  become: yes


  tasks:
    - copy:
       src: /var/project/master-repo
       dest: /etc/yum.repos.d/master.repo


    - name: Yum Updater
      command: yum -y update 


    - name: pip install
      yum: name=python-pip state=present


    - name: Docker-py Install (needed for docker<--->ansible)
      pip: name=docker-py state=present
 
    - name: Docker Install
      yum: name=docker state=present

    - name: Start Docker engine
      service: name=docker state=started


    - name: upload the site directory to the docker host
      synchronize: src=site dest=/tmp


    - name: build the image
      docker_image: >
        name=ansible-docker
        tag=01
        path=/tmp/site
        state=present


    - name: Run COntainer
      docker:
        name: site1
        image: "ansible-docker:01"
        state: reloaded
        publish_all_ports: yes

