---
- hosts: all
  become: yes


  tasks:
    - copy:
       src: /var/project/master-repo
       dest: /etc/yum.repos.d/master.repo


    - name: Yum Updater
      command: yum -y update 


    - name: pip install
      yum: name=python-pip state=present


    - name: Docker-py Install (needed for docker<--->ansible)
      pip: name=docker-py state=present
 
    - name: Docker Install
      yum: name=docker state=present

    - name: Start Docker engine
      service: name=docker state=started

    - include: main.yaml
